# Template file for cluster-insight master in debug mode.
# Pull the binary from Docker Hub only if it missing on the local machine.
# Always run the master in debug mode.
# Expose the master as a service and also on local port 5555.
# See cluster-insight-master-controller.yaml for running the
# cluster-insight master in production mode.
kind: ReplicationController
apiVersion: v1
metadata: 
  name: cluster-insight-master-controller-v1
  namespace: default
  labels: 
    k8s-app: cluster-insight
    version: v1
spec: 
  replicas: 1
  selector: 
    k8s-app: cluster-insight
    cluster-insight-mode: master
    version: v1
  template: 
    metadata: 
      labels: 
        k8s-app: cluster-insight
        cluster-insight-mode: master
        version: v1
    spec: 
      containers: 
        - 
          name: cluster-insight
          image: kubernetes/cluster-insight:latest
          imagePullPolicy: IfNotPresent
          ports: 
            - 
              name: cluster-insight
              containerPort: 5555
              hostPort: 5555
              protocol: TCP
          env: 
            - 
              name: CLUSTER_INSIGHT_MODE
              value: master
          command:
            - "python"
            - "./cluster_insight.py"
            - "--debug"
