# Template file for cluster-insight master in production mode.
# Always pull the latest binary from Docker Hub.
# Always run the master in production mode.
# Expose the master only as a service.
# See cluster-insight-master-controller-debug.yaml for running the
# cluster-insight master in debug mode.
kind: ReplicationController
apiVersion: v1
metadata: 
  name: cluster-insight-master-controller-v1
  namespace: default
  labels: 
    k8s-app: cluster-insight
    version: v1
spec: 
  replicas: 1
  selector: 
    k8s-app: cluster-insight
    cluster-insight-mode: master
    version: v1
  template: 
    metadata: 
      labels: 
        k8s-app: cluster-insight
        cluster-insight-mode: master
        version: v1
    spec: 
      containers: 
        - 
          name: cluster-insight
          # Change the tag to the latest released image.
          image: kubernetes/cluster-insight:2015-07-01
          # Do not change the image pull policy to "Always" because Docker Hub
          # may not be able to respond in time.
          imagePullPolicy: IfNotPresent
          ports: 
            - 
              name: cluster-insight
              containerPort: 5555
              protocol: TCP
          env: 
            - 
              name: CLUSTER_INSIGHT_MODE
              value: master
