machine:
  pre:
    - sudo docker -d -e lxc -s btrfs -H tcp://0.0.0.0:2375:
        background: true
    - curl --retry 15 --retry-delay 3 -v http://172.17.42.1:2375/version
  environment:
    REPO: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
    DOCKER_HOST: tcp://172.17.42.1:2375

dependencies:
  pre:
    - docker version
    - go get github.com/tcnksm/ghr
    - make validate
  override:
    - make binary

test:
  override:
    - make test-unit
    - make MAKE_DOCKER_HOST=$DOCKER_HOST test-integration
  post:
    - make crossbinary
    - make image

deployment:
  hub:
    branch: master
    commands:
      - ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace --prerelease v1.0 dist/
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - docker push ${REPO,,}:latest
      - docker tag ${REPO,,}:latest ${REPO,,}:$CIRCLE_SHA1
      - docker push ${REPO,,}:$CIRCLE_SHA1
