language: go
go:
    - 1.1.1
      #- tip
before_install:
    - cat /proc/sys/kernel/osrelease
install:
    - go get github.com/cznic/kv
    - patch -Nu /home/travis/gopath/src/github.com/cznic/fileutil/fileutil_linux.go fileutil_linux.go.patch
