tomcat:
  #image: ecloud/tomcat 
  build: tomcat
  # command: docker run -it --name="ecloud_tomcat" -p 8080:8080 ecloud/tomcat
  ports:
    - "8080:8080"
  links:
    - cassandra:cassandra
    - swift:swift
    - zookeeper:zk
    - kafka:kafka

cassandra:
  #image: ecloud/cassandra
  build: cassandra
  ports:
    - "9042:9042"
    - "9160:9160"

swift: 
  #image: ecloud/swift
  build: docker-swift-onlyone
  ports:
    - "8888:8888"
  volumes: 
    - /srv

zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181"
    - "22"
nimbus:
  image: wurstmeister/storm-nimbus
  ports:
    - "3773"
    - "3772"
    - "6627"
    - "22"
  links: 
    - zookeeper:zk
supervisor:
  image: wurstmeister/storm-supervisor
  ports:
    - "8000"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
ui:
  image: wurstmeister/storm-ui
  ports:
    - "49080:8080"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk     
kafka: 
  image: wurstmeister/kafka
  ports:
    - "9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

elasticsearch:
  image: tutum/elasticsearch
  ports:
    - "9200:9200"
  environment:
    ELASTICSEARCH_USER: admin
    ELASTICSEARCH_PASS: password