redis:
  image: redis
  ports:
    - "6379:6379"
  volumes:
    - ./data/redis:/data
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes --no-appendfsync-on-rewrite yes

nginx:
  image: klokantech/nginx
  ports:
    - "80:80"
  links:
    - embed
  volumes:
    - nginx/:/etc/nginx/conf.d/
    - .htpasswd:/etc/nginx/.htpasswd

embed:
  build: ./embed
  command: bash -c "/usr/bin/python /usr/local/src/hawk/db_sql_create.py && /usr/local/bin/supervisord -c /etc/supervisord/supervisord.conf"
  expose:
    - "5000"
  links:
    - redis
  volumes:
    - ./embed:/usr/local/src/hawk/
    - ./data/batch:/data/batch
    - ./data/sql:/data/sql
  environment:
    - SERVER_NAME=media.embedr.eu
    - IIIF_SERVER=iiif.embedr.eu
    - REDIS_SERVER=redis
    - REDIS_PORT_NUMBER=6379
    - SQL_DB_URL=/data/sql/db.db

ingest:
  build: ./ingest
  links:
    - redis
  volumes:
    - ./embed:/usr/local/src/hawk/
    - ./data/tmp:/tmp
  environment:
    - C_FORCE_ROOT=true
    - REDIS_SERVER=redis
    - REDIS_PORT_NUMBER=6379
    - AWS_ACCESS_KEY_ID=
    - AWS_SECRET_ACCESS_KEY=
    - S3_CHUNK_SIZE=52428800
    - S3_HOST=s3.eu-central-1.amazonaws.com
    - S3_DEFAULT_BUCKET=storage.hawk.bucket
    - MAX_TASK_REPEAT=5
    - URL_OPEN_TIMEOUT=10
    - CLOUDSEARCH_REGION=eu-central-1
    - CLOUDSEARCH_ITEM_DOMAIN=hawk
  command: bash -c "celery --app=app.task_queue.task_queue worker -E -l warning --workdir=/usr/local/src/hawk/ --autoscale=10,3 --hostname worker1.%h && celery --app=app.task_queue.task_queue worker -E -l warning --workdir=/usr/local/src/hawk/ --autoscale=10,3 --hostname worker2.%h"
