# rules
[backends]
  [backends.backend1]
    [backends.backend1.LoadBalancer]
      method = "drr"
    [backends.backend1.servers.server1]
    url = "http://127.0.0.1:8080"
    weight = 1
  [backends.backend2]
    [backends.backend2.LoadBalancer]
      method = "drr"
    [backends.backend2.servers.server1]
    url = "http://127.0.0.1:7789"
    weight = 1
  [backends.backend3]
    [backends.backend3.LoadBalancer]
      method = "drr"
    [backends.backend3.servers.server1]
    url = "http://127.0.0.1:8888"
    weight = 1
  [backends.backend4]
    [backends.backend4.LoadBalancer]
      method = "drr"
    [backends.backend4.servers.server1]
    url = "http://127.0.0.1:8888"
    weight = 1

[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.search]
    rule = "PathPrefix"
    value = "/search/" 
  [frontends.frontend2]
  backend = "backend2"
    [frontends.frontend1.routes.add]
    rule = "PathPrefix"
    value = "/add/"
  [frontends.frontend3]
  backend = "backend3"
    [frontends.frontend1.routes.bulk]
    rule = "PathPrefix"
    value = "/bulk/"
  [frontends.frontend4]
  backend = "backend4"
    [frontends.frontend1.routes.admin]
    rule = "PathPrefix"
    value = "/admin"
