apiVersion: v1
kind: ReplicationController
metadata:
  name: vmx-routeur-nodejs
  labels:
    name: vmx-routeur-nodejs
spec:
  replicas: 20
  selector:
    name: vmx-routeur-nodejs
  template:
    metadata:
      labels:
        name: vmx-routeur-nodejs
    spec:
      containers:
      - name: vmx-routeur-nodejs
        image: lucmichalski/vmx-proxy:latest
        ports:
        - containerPort: 2424
        volumeMounts:
          - mountPath: /www/false-positives
            name: falsepositives
          - mountPath: /www/public
            name: data
      volumes:
        - name: falsepositives
        - name: data
