registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_STORAGE_S3_ACCESSKEY: awsaccesskey
    REGISTRY_STORAGE_S3_SECRETKEY: secretkey
    REGISTRY_STORAGE_S3_REGION: region
    REGISTRY_STORAGE_S3_BUCKET: bucket
    REGISTRY_STORAGE_S3_ENCRYPT: true
    REGISTRY_STORAGE_S3_SECURE: true
    REGISTRY_STORAGE_S3_V4AUTH: true
    REGISTRY_STORAGE_S3_CHUNKSIZE: 5242880
    REGISTRY_STORAGE_S3_ROOTDIRECTORY: /s3/object/name/prefix
