elasticsearch:
  name: elasticsearch
  image: lucmichalski/elasticsearch:kube-vs-metrics
  volumes:
    - /opt/data/elasticsearch:/var/lib/elasticsearch
  restart: always

logstash:
  name: logstash
  image: lumichalski/logstash:kube-vs-metrics
  volumes:
    - /opt/logs:/opt/logs
    - ./logstash/conf.d:/etc/logstash/conf.d
    - ./logstash/mappings:/etc/logstash/mappings
    - ./logstash/patterns:/opt/logstash/patterns_extra
  ports:
    - 5000
  links:
    - elasticsearch
  restart: always

kibana:
  image: lucmichalski/kibana:kube-vs-metrics
  links:
    - elasticsearch
  restart: always

nginx:
  name: nginx
  image: lucmichalski/nginx:kube-vs-metrics
  ports:
    - 443
  links:
    - kibana
  restart: always

forwarder:
  name: forwarder
  image: lucmichalski/forwarder:kube-vs-metrics
  links:
    - logstash
  volumes:
    - /opt/logs:/opt/logs
    - /usr/local/bin:/target

hdfs:
  name: hdfs
  image: lucmichalski/hdfs:kube-vs-metrics
  command: /etc/bootstrap.sh -d -bash

mazerunner:
  name: mazerunner
  image: lucmichalski/mazerunner:kube-vs-metrics
  links:
   - hdfs

graphdb:
  name: graphdb 
  build: lucmichalski/graphdb:kube-vs-metrics
  ports:
   - 7474
   - 1337
  volumes:
   - /opt/logs:/opt/logs
   - /opt/data:/opt/data
  links:
   - mazerunner
   - hdfs
