elasticsearch:
  build: elasticsearch
  volumes:
    - /opt/data/elasticsearch:/var/lib/elasticsearch
  restart: always

logstash:
  build: logstash
  volumes:
    - /opt/logs:/opt/logs
    - ./logstash/conf.d:/etc/logstash/conf.d
    - ./logstash/mappings:/etc/logstash/mappings
    - ./logstash/patterns:/opt/logstash/patterns_extra
  ports:
    - "5000:5000"
  links:
    - elasticsearch
  restart: always

kibana:
  build: kibana
  links:
    - elasticsearch
  restart: always

nginx:
  build: nginx
  ports:
    - "1443:443"
  links:
    - kibana
  restart: always

forwarder:
  build: forwarder
  links:
    - logstash
  volumes:
    - /opt/logs:/opt/logs
    - /usr/local/bin:/target

hdfs:
  build: hdfs
  command: /etc/bootstrap.sh -d -bash

mazerunner:
  build: mazerunner
  links:
   - hdfs

graphdb:
  build: graphdb
  ports:
   - "7474:7474"
   - "1337:1337"
  volumes:
   - /opt/logs:/opt/logs
   - /opt/data:/opt/data
  links:
   - mazerunner
   - hdfs
